package com.alexjprog.deezerforandroid.util

import java.util.concurrent.TimeUnit

const val FIREBASE_MEDIA_ID_KEY = "id"
const val FIREBASE_MEDIA_TYPE_KEY = "type"

const val MEDIA_ID_PLAYER_ARG_KEY = "playableMediaId"
const val MEDIA_TYPE_PLAYER_ARG_KEY = "playableMediaType"

const val CHARTS_PREVIEW_SIZE = 10
const val FLOW_PREVIEW_SIZE = 10
const val RECOMMENDATIONS_PREVIEW_SIZE = 10

const val CONTENT_PAGE_SIZE = 20

const val SEARCH_PAGE_SIZE = 20

const val MAX_CONTENT_NAMES_IN_EDIT_SELECTION_UPDATE = 4
const val MAX_CONTENT_NAMES_IN_EDIT_RELEASES_UPDATE = 3

const val EDIT_SELECTION_UPDATE_INTERVAL = 1L
const val EDIT_RELEASES_UPDATE_INTERVAL = 1L

val EDIT_SELECTION_UPDATE_INTERVAL_TIME_UNIT = TimeUnit.DAYS
val EDIT_RELEASES_UPDATE_INTERVAL_TIME_UNIT = TimeUnit.DAYS

const val EDIT_SELECTION_UPDATE_FLEX_INTERVAL = 15L
const val EDIT_RELEASES_UPDATE_FLEX_INTERVAL = 15L

val EDIT_SELECTION_UPDATE_FLEX_INTERVAL_TIME_UNIT = TimeUnit.MINUTES
val EDIT_RELEASES_UPDATE_FLEX_INTERVAL_TIME_UNIT = TimeUnit.MINUTES
